using System;
using System.Collections.Generic;

namespace ApiTesis.Models.Register
{
    public partial class Register
    {
        public int Id { get; set; }
        public string Airms { get; set; }
        public string Afirms { get; set; }
        public string AihrmsCal { get; set; }
        public string Avrms { get; set; }
        public string Afvrms { get; set; }
        public string AvhrmsCal { get; set; }
        public string Aithd { get; set; }
        public string Avthd { get; set; }
        public string Angle0 { get; set; }
        public string Apf { get; set; }
        public string Apf1Cal { get; set; }
        public string Awatt { get; set; }
        public string Ap1Cal { get; set; }
        public string AphCal { get; set; }
        public string Avar { get; set; }
        public string Ava { get; set; }
        public string AshCal { get; set; }
        public string As1Cal { get; set; }
        public string AsnCal { get; set; }
        public string AdiCal { get; set; }
        public string AdvCal { get; set; }
        public string AdhCal { get; set; }
        public string AnCal { get; set; }
        public string Nirms { get; set; }
        public string Afvarhr { get; set; }
        public string Afwatthr { get; set; }
        public string Avahr { get; set; }
        public string Avarhr { get; set; }
        public string Awatthr { get; set; }
        public string Birms { get; set; }
        public string Bfirms { get; set; }
        public string BihrmsCal { get; set; }
        public string Bvrms { get; set; }
        public string Bfvrms { get; set; }
        public string BvhrmsCal { get; set; }
        public string Bithd { get; set; }
        public string Bvthd { get; set; }
        public string Angle1 { get; set; }
        public string Bpf { get; set; }
        public string Bpf1Cal { get; set; }
        public string Bwatt { get; set; }
        public string Bp1Cal { get; set; }
        public string BphCal { get; set; }
        public string Bvar { get; set; }
        public string Bva { get; set; }
        public string BshCal { get; set; }
        public string Bs1Cal { get; set; }
        public string BsnCal { get; set; }
        public string BdiCal { get; set; }
        public string BdvCal { get; set; }
        public string BdhCal { get; set; }
        public string BnCal { get; set; }
        public string Bfvarhr { get; set; }
        public string Bfwatthr { get; set; }
        public string Bvahr { get; set; }
        public string Bvarhr { get; set; }
        public string Bwatthr { get; set; }
        public string Cirms { get; set; }
        public string Cfirms { get; set; }
        public string CihrmsCal { get; set; }
        public string Cvrms { get; set; }
        public string Cfvrms { get; set; }
        public string CvhrmsCal { get; set; }
        public string Cithd { get; set; }
        public string Cvthd { get; set; }
        public string Angle2 { get; set; }
        public string Cpf { get; set; }
        public string Cpf1Cal { get; set; }
        public string Cwatt { get; set; }
        public string CpCal { get; set; }
        public string Cp1Cal { get; set; }
        public string CphCal { get; set; }
        public string Cvar { get; set; }
        public string Cva { get; set; }
        public string CshCal { get; set; }
        public string Cs1Cal { get; set; }
        public string CsnCal { get; set; }
        public string CdiCal { get; set; }
        public string CdvCal { get; set; }
        public string CdhCal { get; set; }
        public string CnCal { get; set; }
        public string Cfvarhr { get; set; }
        public string Cfwatthr { get; set; }
        public string Cvahr { get; set; }
        public string Cvarhr { get; set; }
        public string Cwatthr { get; set; }
        public string Isum { get; set; }
        public string IeCal { get; set; }
        public string Ie1Cal { get; set; }
        public string IehCal { get; set; }
        public string VabCal { get; set; }
        public string Vab1Cal { get; set; }
        public string VabhCal { get; set; }
        public string VbcCal { get; set; }
        public string Vbc1Cal { get; set; }
        public string VbchCal { get; set; }
        public string VcaCal { get; set; }
        public string Vca1Cal { get; set; }
        public string VcahCal { get; set; }
        public string VeCal { get; set; }
        public string Ve1Cal { get; set; }
        public string VehCal { get; set; }
        public string SeCal { get; set; }
        public string Se1Cal { get; set; }
        public string SehCal { get; set; }
        public string DeiCal { get; set; }
        public string DevCal { get; set; }
        public string SenCal { get; set; }
        public string ThdevCal { get; set; }
        public string ThdeiCal { get; set; }
        public string PeCal { get; set; }
        public string PehCal { get; set; }
        public string PfeCal { get; set; }
        public string DehCal { get; set; }
        public DateTime Datetime { get; set; }
    }
}
